# Generated by Django 5.1.1 on 2024-12-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Owner Name')),
                ('shop_name', models.CharField(max_length=255, verbose_name='Shop Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Owner Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('shop_address', models.TextField(verbose_name='Shop Address')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('registered_on', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
    ]
