# Generated by Django 5.1.1 on 2024-12-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, verbose_name='Shop Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('website_link', models.URLField(blank=True, default=None, max_length=500, null=True, verbose_name='Shop Website Link')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='shop_address',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='shopowner',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='shopowner.shop', verbose_name='Shop'),
            preserve_default=False,
        ),
    ]
